# Generated by Django 5.2.4 on 2025-08-22 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commonuserprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='commonuserprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='commonuserprofile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='commonuserprofile',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='commonuserprofile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='commonuserprofile',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='commonuserprofile',
            name='state',
        ),
        migrations.RemoveField(
            model_name='commonuserprofile',
            name='zip_code',
        ),
        migrations.RemoveField(
            model_name='serviceproviderprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='serviceproviderprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='serviceproviderprofile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='serviceproviderprofile',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='serviceproviderprofile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='serviceproviderprofile',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='serviceproviderprofile',
            name='state',
        ),
        migrations.RemoveField(
            model_name='serviceproviderprofile',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Masculino'), ('female', 'Femenino'), ('other', 'Otro')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
